title: NetHack Challenge
description: >-
  NeurIPS 2021 NetHack Challenge website
description_v2: >-
  Welcome to the NetHack&nbsp;Challenge
description_subhead_v2: >-
  At Neurips 2021
baseurl: ""
url: ""
logo: assets/images/logo.png

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

show_downloads: true
twitter_url: "https://twitter.com/NetHack_LE"
discord_url: "https://discord.gg/zkFWQmSWBA"
github_url: "https://github.com/facebookresearch/nle"
AIcrowd_url: "https://www.aicrowd.com/challenges/neurips-2021-nethack-challenge"

twitter_icon: "assets/images/Twitter_Icon.svg"
discord_icon: "assets/images/Discord_Icon.svg"
github_icon: "assets/images/GitHub_Icon.svg"
paper_icon: "assets/images/Paper_Icon.svg"
aicrowd_logo: "assets/images/AIcrowd_Logo.png"
right_dark_arrow: "assets/images/Right-Dark.svg"
right_light_arrow: "assets/images/Right-Light.svg"

github:
  is_project_page: false
  is_user_page: false
